import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import Lenis from '@/components/lenis';
import Footer from '@/components/footer';
import Header from '@/components/header/header';
import { client } from '@/sanity/lib/client';
import { GENERAL_INFO_QUERY } from '@/sanity/lib/queries';
import { GENERAL_INFO_QUERYResult } from '@/sanity.types';

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['300', '400'],
  style: ['normal', 'italic'],
  variable: '--font-dm-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { generalInfo, blinkdraft }: GENERAL_INFO_QUERYResult =
    await client.fetch(GENERAL_INFO_QUERY);

  if (!generalInfo || !blinkdraft) {
    return <div>No general info or blinkdraft data found</div>;
  }

  return (
    <html lang='en'>
      <body className={`${dmSans.variable} antialiased`}>
        <Header bdkLogo={generalInfo?.logo} blinkdraftLogo={blinkdraft.logo} />
        <Lenis>{children}</Lenis>
        <Footer generalInfo={generalInfo} blinkdraftLogo={blinkdraft.logo} />
      </body>
    </html>
  );
}
