import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const helveticaOblique = localFont({
  src: [
    {
      path: '../fonts/HelveticaLTStd-Obl.woff',
      weight: '400',
    },
  ],
  variable: '--font-helvetica-oblique',
});

const helvetica = localFont({
  src: [
    {
      path: '../fonts/HelveticaNeueLTCom-Roman.woff',
      weight: '400',
    },
  ],
  variable: '--font-helvetica',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${helveticaOblique.variable} ${helvetica.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
